### ISSUE TITLE
Cannot "copy to slot" delubrum savage markers

### ISSUE THREAD

**Issue by quisquous** [PunishedPineapple/WaymarkPresetPlugin#9] opened 2021-03-10 01:48 UTC
I have several marker presets for Delubrum Savage, some imported from discord, and some imported from the game.  They all import to the same category, "Unknown Duty".  When I do "Copy to slot" for any of the presets for this zone (761), they do not override my in-game slots.  When I do "Copy to slot" for any presets for other zones, they do correctly override my in-game slots.

I am using version v1.1.2.0.

Here is all presets exported, if that helps:
```
{"Name":"Rotated Seed Stacks","MapID":750,"A":{"X":100.323,"Y":0.0,"Z":81.414,"ID":0,"Active":true},"B":{"X":118.452,"Y":0.0,"Z":98.826,"ID":1,"Active":true},"C":{"X":99.917,"Y":0.0,"Z":118.403,"ID":2,"Active":true},"D":{"X":81.554,"Y":0.0,"Z":98.387,"ID":3,"Active":true},"One":{"X":103.959,"Y":0.0,"Z":91.183,"ID":4,"Active":true},"Two":{"X":108.996,"Y":0.0,"Z":103.747,"ID":5,"Active":true},"Three":{"X":96.093,"Y":0.0,"Z":108.823,"ID":6,"Active":true},"Four":{"X":91.183,"Y":0.0,"Z":96.37,"ID":7,"Active":true}}
{"Name":"Uptime Orb Markers","MapID":748,"A":{"X":99.848,"Y":0.0,"Z":90.6,"ID":0,"Active":true},"B":{"X":105.227,"Y":0.0,"Z":99.882,"ID":1,"Active":true},"C":{"X":99.942,"Y":0.0,"Z":109.107,"ID":2,"Active":true},"D":{"X":94.487,"Y":0.0,"Z":99.925,"ID":3,"Active":true},"One":{"X":107.186,"Y":0.0,"Z":92.697,"ID":4,"Active":true},"Two":{"X":106.93,"Y":0.0,"Z":106.535,"ID":5,"Active":true},"Three":{"X":92.951,"Y":0.0,"Z":106.744,"ID":6,"Active":true},"Four":{"X":92.464,"Y":0.0,"Z":92.911,"ID":7,"Active":true}}
{"Name":"Braindead Markers","MapID":752,"A":{"X":100.017,"Y":0.0,"Z":90.428,"ID":0,"Active":true},"B":{"X":109.975,"Y":0.0,"Z":99.917,"ID":1,"Active":true},"C":{"X":99.931,"Y":0.0,"Z":109.73,"ID":2,"Active":true},"D":{"X":89.936,"Y":0.0,"Z":99.954,"ID":3,"Active":true},"One":{"X":107.04,"Y":0.0,"Z":92.945,"ID":4,"Active":true},"Two":{"X":106.774,"Y":0.0,"Z":106.985,"ID":5,"Active":true},"Three":{"X":93.032,"Y":0.0,"Z":106.952,"ID":6,"Active":true},"Four":{"X":92.774,"Y":0.0,"Z":92.709,"ID":7,"Active":true}}
{"Name":"Door Bili Bili Lions","MapID":759,"A":{"X":-0.075,"Y":75.0,"Z":-84.81,"ID":0,"Active":true},"B":{"X":9.953,"Y":75.0,"Z":-75.074,"ID":1,"Active":true},"C":{"X":-0.011,"Y":75.0,"Z":-65.028,"ID":2,"Active":true},"D":{"X":-9.941,"Y":75.0,"Z":-75.06,"ID":3,"Active":true},"One":{"X":5.98,"Y":75.0,"Z":-80.973,"ID":4,"Active":true},"Two":{"X":6.037,"Y":75.0,"Z":-69.202,"ID":5,"Active":true},"Three":{"X":-6.008,"Y":75.0,"Z":-69.135,"ID":6,"Active":true},"Four":{"X":-6.019,"Y":75.0,"Z":-80.961,"ID":7,"Active":true}}
{"Name":"Oracle With Intercardinal Outside","MapID":759,"A":{"X":-0.075,"Y":75.0,"Z":-84.81,"ID":0,"Active":true},"B":{"X":9.953,"Y":75.0,"Z":-75.074,"ID":1,"Active":true},"C":{"X":-0.011,"Y":75.0,"Z":-65.028,"ID":2,"Active":true},"D":{"X":-9.941,"Y":75.0,"Z":-75.06,"ID":3,"Active":true},"One":{"X":12.751,"Y":75.0,"Z":-88.134,"ID":4,"Active":true},"Two":{"X":13.042,"Y":75.0,"Z":-62.052,"ID":5,"Active":true},"Three":{"X":-13.058,"Y":75.0,"Z":-62.053,"ID":6,"Active":true},"Four":{"X":-13.017,"Y":75.0,"Z":-88.147,"ID":7,"Active":true}}
{"Name":"Xeno Full U[time Lions","MapID":759,"A":{"X":8.949,"Y":75.0,"Z":-91.943,"ID":0,"Active":true},"B":{"X":9.236,"Y":75.0,"Z":-58.104,"ID":1,"Active":true},"C":{"X":-5.5,"Y":75.0,"Z":-66.761,"ID":2,"Active":true},"D":{"X":-5.29,"Y":75.0,"Z":-83.374,"ID":3,"Active":true},"One":{"X":6.466,"Y":75.0,"Z":-83.877,"ID":4,"Active":true},"Two":{"X":6.575,"Y":75.0,"Z":-66.777,"ID":5,"Active":true},"Three":{"X":-2.667,"Y":75.0,"Z":-72.214,"ID":6,"Active":true},"Four":{"X":-2.79,"Y":75.0,"Z":-77.782,"ID":7,"Active":true}}
{"Name":"Puddle Positions, W=1, E=2","MapID":658,"A":{"X":83.0,"Y":0.0,"Z":83.0,"ID":0,"Active":true},"B":{"X":117.0,"Y":0.0,"Z":83.0,"ID":1,"Active":true},"C":{"X":83.0,"Y":0.0,"Z":117.0,"ID":2,"Active":true},"D":{"X":117.0,"Y":0.0,"Z":117.0,"ID":3,"Active":true},"One":{"X":91.0,"Y":0.0,"Z":100.0,"ID":4,"Active":true},"Two":{"X":109.0,"Y":0.0,"Z":100.0,"ID":5,"Active":true},"Three":{"X":100.0,"Y":0.0,"Z":91.0,"ID":6,"Active":true},"Four":{"X":100.0,"Y":0.0,"Z":109.0,"ID":7,"Active":true}}
{"Name":"Xeno Full U[time Lions Symmetrical","MapID":759,"A":{"X":-6.5,"Y":75.0,"Z":-83.88,"ID":0,"Active":true},"B":{"X":-6.5,"Y":75.0,"Z":-66.12,"ID":1,"Active":true},"C":{"X":2.7,"Y":75.0,"Z":-72.2,"ID":2,"Active":true},"D":{"X":2.7,"Y":75.0,"Z":-77.8,"ID":3,"Active":true},"One":{"X":6.5,"Y":75.0,"Z":-83.88,"ID":4,"Active":true},"Two":{"X":6.5,"Y":75.0,"Z":-66.12,"ID":5,"Active":true},"Three":{"X":-2.7,"Y":75.0,"Z":-72.2,"ID":6,"Active":true},"Four":{"X":-2.7,"Y":75.0,"Z":-77.8,"ID":7,"Active":true}}
{"Name":"Imported","MapID":759,"A":{"X":-6.5,"Y":75.0,"Z":-83.875,"ID":0,"Active":true},"B":{"X":-6.5,"Y":75.0,"Z":-66.12,"ID":1,"Active":true},"C":{"X":2.7,"Y":75.0,"Z":-72.199,"ID":2,"Active":true},"D":{"X":2.7,"Y":75.0,"Z":-77.8,"ID":3,"Active":true},"One":{"X":6.5,"Y":75.0,"Z":-83.875,"ID":4,"Active":true},"Two":{"X":6.5,"Y":75.0,"Z":-66.12,"ID":5,"Active":true},"Three":{"X":-2.7,"Y":75.0,"Z":-72.199,"ID":6,"Active":true},"Four":{"X":-2.7,"Y":75.0,"Z":-77.8,"ID":7,"Active":true}}
{"Name":"Trinity Seeker","MapID":761,"A":{"X":0.044,"Y":8.0,"Z":267.991,"ID":0,"Active":true},"B":{"X":9.711,"Y":7.999,"Z":277.83,"ID":1,"Active":true},"C":{"X":0.0,"Y":7.999,"Z":288.036,"ID":2,"Active":true},"D":{"X":-9.972,"Y":7.999,"Z":277.746,"ID":3,"Active":true},"One":{"X":7.164,"Y":7.999,"Z":270.572,"ID":4,"Active":true},"Two":{"X":7.148,"Y":8.0,"Z":285.262,"ID":5,"Active":true},"Three":{"X":-7.143,"Y":8.0,"Z":285.182,"ID":6,"Active":true},"Four":{"X":-7.417,"Y":7.999,"Z":270.255,"ID":7,"Active":true}}
{"Name":"Dahu","MapID":761,"A":{"X":82.469,"Y":11.999,"Z":122.552,"ID":0,"Active":true},"B":{"X":97.504,"Y":12.0,"Z":138.394,"ID":1,"Active":true},"C":{"X":81.968,"Y":12.0,"Z":153.86,"ID":2,"Active":true},"D":{"X":66.171,"Y":12.0,"Z":137.721,"ID":3,"Active":true},"One":{"X":96.477,"Y":12.0,"Z":114.511,"ID":4,"Active":true},"Two":{"X":96.712,"Y":12.0,"Z":161.669,"ID":5,"Active":true},"Three":{"X":67.29,"Y":12.0,"Z":161.63,"ID":6,"Active":true},"Four":{"X":67.528,"Y":11.999,"Z":114.867,"ID":7,"Active":true}}
{"Name":"Queen's Guard","MapID":761,"A":{"X":244.023,"Y":-86.0,"Z":-182.258,"ID":0,"Active":true},"B":{"X":264.118,"Y":-86.0,"Z":-161.98,"ID":1,"Active":true},"C":{"X":244.004,"Y":-86.0,"Z":-141.883,"ID":2,"Active":true},"D":{"X":223.883,"Y":-86.0,"Z":-162.015,"ID":3,"Active":true},"One":{"X":258.242,"Y":-86.0,"Z":-176.247,"ID":4,"Active":true},"Two":{"X":258.199,"Y":-86.0,"Z":-147.768,"ID":5,"Active":true},"Three":{"X":229.716,"Y":-86.0,"Z":-147.793,"ID":6,"Active":true},"Four":{"X":229.697,"Y":-86.0,"Z":-176.254,"ID":7,"Active":true}}
{"Name":"Bozjan Phantom","MapID":761,"A":{"X":184.044,"Y":-96.999,"Z":-388.976,"ID":0,"Active":true},"B":{"X":195.995,"Y":-96.999,"Z":-389.214,"ID":1,"Active":true},"C":{"X":208.061,"Y":-96.999,"Z":-389.014,"ID":2,"Active":true},"D":{"X":220.072,"Y":-96.999,"Z":-389.17,"ID":3,"Active":true},"One":{"X":183.76,"Y":-96.999,"Z":-347.163,"ID":4,"Active":true},"Two":{"X":195.867,"Y":-96.999,"Z":-347.054,"ID":5,"Active":true},"Three":{"X":208.082,"Y":-96.999,"Z":-347.016,"ID":6,"Active":true},"Four":{"X":220.139,"Y":-96.999,"Z":-347.061,"ID":7,"Active":true}}
{"Name":"Trinity Avowed","MapID":761,"A":{"X":-272.224,"Y":-182.0,"Z":-105.831,"ID":0,"Active":true},"B":{"X":-248.442,"Y":-182.0,"Z":-81.991,"ID":1,"Active":true},"C":{"X":-272.002,"Y":-182.0,"Z":-58.56,"ID":2,"Active":true},"D":{"X":-295.616,"Y":-182.0,"Z":-81.923,"ID":3,"Active":true},"One":{"X":-281.97,"Y":-182.0,"Z":-92.124,"ID":4,"Active":true},"Two":{"X":-272.146,"Y":-182.0,"Z":-91.688,"ID":5,"Active":true},"Three":{"X":-282.21,"Y":-182.0,"Z":-81.691,"ID":6,"Active":true},"Four":{"X":-272.131,"Y":-182.0,"Z":-81.833,"ID":7,"Active":true}}
{"Name":"Stygimoloch Lord","MapID":761,"A":{"X":-415.925,"Y":-191.0,"Z":-211.601,"ID":0,"Active":true},"B":{"X":-388.053,"Y":-191.0,"Z":-183.986,"ID":1,"Active":true},"C":{"X":-416.02,"Y":-191.0,"Z":-156.472,"ID":2,"Active":true},"D":{"X":-443.842,"Y":-191.0,"Z":-183.999,"ID":3,"Active":true},"One":{"X":-396.454,"Y":-191.0,"Z":-202.615,"ID":4,"Active":true},"Two":{"X":-396.679,"Y":-191.0,"Z":-164.644,"ID":5,"Active":true},"Three":{"X":-435.329,"Y":-191.0,"Z":-164.539,"ID":6,"Active":true},"Four":{"X":-435.813,"Y":-191.0,"Z":-203.763,"ID":7,"Active":true}}
{"Name":"The Queen","MapID":761,"A":{"X":-292.15,"Y":-175.0,"Z":-415.795,"ID":0,"Active":true},"B":{"X":-281.64,"Y":-175.0,"Z":-414.869,"ID":1,"Active":true},"C":{"X":-261.941,"Y":-175.0,"Z":-414.531,"ID":2,"Active":true},"D":{"X":-252.168,"Y":-175.0,"Z":-414.903,"ID":3,"Active":true},"One":{"X":-272.196,"Y":-175.0,"Z":-434.119,"ID":4,"Active":true},"Two":{"X":-272.078,"Y":-175.0,"Z":-424.67,"ID":5,"Active":true},"Three":{"X":-272.119,"Y":-175.0,"Z":-404.446,"ID":6,"Active":true},"Four":{"X":-272.056,"Y":-175.0,"Z":-394.801,"ID":7,"Active":true}}
{"Name":"Imported","MapID":750,"A":{"X":100.322,"Y":0.0,"Z":81.414,"ID":0,"Active":true},"B":{"X":118.452,"Y":0.0,"Z":98.825,"ID":1,"Active":true},"C":{"X":99.916,"Y":0.0,"Z":118.402,"ID":2,"Active":true},"D":{"X":81.554,"Y":0.0,"Z":98.387,"ID":3,"Active":true},"One":{"X":103.958,"Y":0.0,"Z":91.182,"ID":4,"Active":true},"Two":{"X":108.996,"Y":0.0,"Z":103.747,"ID":5,"Active":true},"Three":{"X":96.093,"Y":0.0,"Z":108.822,"ID":6,"Active":true},"Four":{"X":91.182,"Y":0.0,"Z":96.37,"ID":7,"Active":true}}
{"Name":"Imported","MapID":750,"A":{"X":100.322,"Y":0.0,"Z":81.414,"ID":0,"Active":true},"B":{"X":118.452,"Y":0.0,"Z":98.825,"ID":1,"Active":true},"C":{"X":99.916,"Y":0.0,"Z":118.402,"ID":2,"Active":true},"D":{"X":81.554,"Y":0.0,"Z":98.387,"ID":3,"Active":true},"One":{"X":103.958,"Y":0.0,"Z":91.182,"ID":4,"Active":true},"Two":{"X":108.996,"Y":0.0,"Z":103.747,"ID":5,"Active":true},"Three":{"X":96.093,"Y":0.0,"Z":108.822,"ID":6,"Active":true},"Four":{"X":91.182,"Y":0.0,"Z":96.37,"ID":7,"Active":true}}
{"Name":"Imported Slime Door?","MapID":761,"A":{"X":-279.979,"Y":-31.0,"Z":425.2,"ID":0,"Active":true},"B":{"X":-280.343,"Y":-31.0,"Z":434.747,"ID":1,"Active":true},"C":{"X":-266.267,"Y":-31.0,"Z":425.452,"ID":2,"Active":true},"D":{"X":-267.786,"Y":-31.0,"Z":435.56,"ID":3,"Active":true},"One":{"X":-273.533,"Y":-31.0,"Z":422.804,"ID":4,"Active":true},"Two":{"X":-273.39,"Y":-31.0,"Z":437.028,"ID":5,"Active":true},"Three":{"X":0.0,"Y":0.0,"Z":0.0,"ID":6,"Active":false},"Four":{"X":0.0,"Y":0.0,"Z":0.0,"ID":7,"Active":false}}
{"Name":"Imported Seeker?","MapID":761,"A":{"X":19.06,"Y":7.999,"Z":272.441,"ID":0,"Active":true},"B":{"X":5.913,"Y":7.999,"Z":297.169,"ID":1,"Active":true},"C":{"X":-19.709,"Y":8.0,"Z":281.365,"ID":2,"Active":true},"D":{"X":-5.485,"Y":7.999,"Z":257.272,"ID":3,"Active":true},"One":{"X":-6.771,"Y":7.999,"Z":273.003,"ID":4,"Active":true},"Two":{"X":7.585,"Y":8.0,"Z":270.706,"ID":5,"Active":true},"Three":{"X":7.235,"Y":7.999,"Z":285.45,"ID":6,"Active":true},"Four":{"X":-7.389,"Y":7.999,"Z":285.551,"ID":7,"Active":true}}
{"Name":"Imported Dahu?","MapID":761,"A":{"X":81.991,"Y":11.999,"Z":111.541,"ID":0,"Active":true},"B":{"X":108.406,"Y":12.0,"Z":141.243,"ID":1,"Active":true},"C":{"X":81.515,"Y":12.0,"Z":165.162,"ID":2,"Active":true},"D":{"X":54.505,"Y":12.0,"Z":141.67,"ID":3,"Active":true},"One":{"X":60.694,"Y":11.999,"Z":121.517,"ID":4,"Active":true},"Two":{"X":101.233,"Y":11.999,"Z":119.373,"ID":5,"Active":true},"Three":{"X":99.268,"Y":12.0,"Z":160.088,"ID":6,"Active":true},"Four":{"X":64.835,"Y":12.0,"Z":160.951,"ID":7,"Active":true}}
```

**Comment by PunishedPineapple** [comment] 2021-03-10 10:05
Should be fixed (from a user standpoint, at least) in latest release.  Will PR to /xlplugins once I get a sample size of more than just myself that it's ok now.

**Comment by rekyuu** [comment] 2021-03-15 02:00
Wanted to chime in and say that the latest commit worked for me. DR Savage no longer shows up as an unknown area and I was able to copy to all my waymark slots.

Maps in the first sub area work but anything beyond that gets wonky, not sure if that needs to swap to different sub-maps or not or if that's even possible.

Thanks for all you do!

![image](https://user-images.githubusercontent.com/14059899/111094059-0082d300-8500-11eb-8dde-a068784aec4e.png)

![image](https://user-images.githubusercontent.com/14059899/111094064-037dc380-8500-11eb-8433-2848b34b6074.png)

![image](https://user-images.githubusercontent.com/14059899/111094170-45a70500-8500-11eb-962f-04adc0752f8d.png)

![image](https://user-images.githubusercontent.com/14059899/111094175-4b044f80-8500-11eb-922a-ff6ead9def88.png)

**Comment by PunishedPineapple** [comment] 2021-03-15 09:24
@rekyuu Thank you for the testing and confirmation!  For the sub-maps, if you expand the map window a bit vertically, there are radio buttons to select the sub-map that you're viewing.  I probably need to figure out a way to make that more clear in the future...  Anyway, I've never been able to find the information to be able to automatically detect and select which sub-map to show (and in the case of waymarks spread across different maps, wouldn't be able to do it even if I knew where to find the bounding coordinates for the submaps), so for now, sub-map viewing is all manual :/

**Comment by rekyuu** [comment] 2021-03-15 23:34
Looks like the map image expands vertically to match the window size which probably knocks them out of view. I'll just make a new issue for it (https://github.com/PunishedPineapple/WaymarkPresetPlugin/issues/10) since it's not as relevant to this one, and we can at least confirm DR copying seems to work as intended now.

**Comment by quisquous** [comment] 2021-03-16 00:22
> Wanted to chime in and say that the latest commit worked for me. DR Savage no longer shows up as an unknown area and I was able to copy to all my waymark slots.

I can confirm this as well.  (Thanks for the speedy fix!!)

**Comment by PunishedPineapple** [comment] 2021-03-16 00:26
Thanks for the confirmation!  Will close this once the new version gets accepted into XLPlugins.

**Closed as completed** 2021-03-18 21:10 UTC
