### ISSUE TITLE
report a bug

### ISSUE THREAD

**Issue by yumozzz** [PunishedPineapple/WaymarkPresetPlugin#32] opened 2022-12-21 10:02 UTC
The Preset Editor will keep flashing when Dalamud option "Use AXIS as default font" is enabled and it won't be easy to edit anything under such circumstance.

**Comment by PunishedPineapple** [comment] 2022-12-22 05:01
Can you post a screenshot of, or the values for, your Dalamud style editor settings (if you’re not on the default style)?  Also, what is your global font scale setting?  I’ve not been able to reproduce any flashing or resizing issues so far.

**Comment by yumozzz** [comment] 2022-12-22 07:27
Well my Dalamud is (maybe) specially modified for CN client so the settings can hardly help but here are the screenshots
![image](https://user-images.githubusercontent.com/98417370/209080312-3a5e0ffe-beb9-45e7-8180-7a275cd97c8b.png)
![image](https://user-images.githubusercontent.com/98417370/209080354-60ddc658-604a-4ed1-8dde-10970fb74e37.png)
 it just keeps switching like this

**Comment by yumozzz** [comment] 2022-12-22 07:30
And I noticed that it won't work when I change Dalamud's language from Chinese to English
This is the setting that cause the problem
![image](https://user-images.githubusercontent.com/98417370/209080911-c894e1e5-8a7f-4ad9-8f9d-a9e014d1f15b.png)

**Comment by yumozzz** [comment] 2022-12-22 07:36
Also, the window will automatically expand like this until it finally starts flashing
![image](https://user-images.githubusercontent.com/98417370/209081602-c7b25746-e24e-4881-a452-71b5ae145602.png)
![image](https://user-images.githubusercontent.com/98417370/209081750-97500c18-db68-4e88-9e68-c4b0ad2e3f9b.png)

**Comment by PunishedPineapple** [comment] 2022-12-22 08:06
I use the AXIS font with no issue, so I don’t know why that’s making a difference.  The expanding window to the side issue was fixed quite some time ago, so I’m surprised you’re seeing it.  It looks like in your case it’s probably that the map view button width is being calculated incorrectly for some reason, but if that were bugged, it should happen to everyone, not just you.

Regardless, if you want to post what your style settings are for like cell padding, item padding, window padding, etc., I’ll double check with those (although it looks like you’re using the default Dalamud style?).

**Comment by PunishedPineapple** [comment] 2022-12-22 08:17
Ok, actually there is a layout bug that could potentially affect this in languages other than English, but I still don’t understand how you’re seeing this happen with the plugin in English.

**Comment by yumozzz** [comment] 2022-12-22 08:26
I have never changed the Dalamud style except for the global font scale (set to 16pt). I check that this problem can appear when I 
use Dalamud Classic or Dalamud Standard. Now I think maybe this is because I'm using CN client, both the game and Dalamud.

**Comment by PunishedPineapple** [comment] 2022-12-22 08:33
Ok, I’m actually able to reproduce this now.  It appears to be a text wrapping bug at certain non-standard global scales.  I’ll see what I can do to fix this.  Sorry for all the back and forth, and thank you for being patient.

**Comment by PunishedPineapple** [comment] 2022-12-24 20:47
This should be fixed in 1.4.3.4.

**Closed as completed by PunishedPineapple** 2022-12-24 20:47 UTC
